# Create an event
POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Py NE",
    "details": "Evento de Py no Nordeste",
    "maximumAttendees": 3
}

###

# Register an attendee
POST http://localhost:3333/events/bef2c7e9-feb1-49b7-a127-d0791e09bd5b/attendees
Content-Type: application/json

{
    "name": "Mary Smith",
    "socialName": "Andre Smith",
    "email": "mary.smith@example.com",
    "age": 35,
    "gender": "female",
    "customGender": "Transsexual",
    "treatAs": "male",
    "accessibility": "Nenhuma"
}

###

# Get an event
GET http://localhost:3333/events/300b8deb-ae7f-43df-8243-441b88436c97

###

# Get an attendees badge
GET http://localhost:3333/events/attendees/g23a76/badge

###

# Check-in attendee
GET http://localhost:3333/attendees/9217g8/check-in

###

# Get event attendee
GET http://localhost:3333/events/bef2c7e9-feb1-49b7-a127-d0791e09bd5b/attendees?query=john
