# Create an event
POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "DevFest",
    "details": "Um evento para Devs em João Pessoa",
    "maximumAttendees": 125
}

###

# Register an attendee
POST http://localhost:3333/events/bef2c7e9-feb1-49b7-a127-d0791e09bd5b/attendees
Content-Type: application/json

{
    "name": "Carlos Garcia",
    "socialName": "Ana Garcia",
    "email": "ana.garcia@gmail.com",
    "age": 29,
    "gender": "male",
    "customGender": "Transgênero",
    "treatAs": "female",
    "accessibility": "Nenhuma"
}

###

# Get an event
GET http://localhost:3333/events/bef2c7e9-feb1-49b7-a127-d0791e09bd5b

###

# Get an attendees badge
GET http://localhost:3333/events/attendees/gcg23d/badge

###

# Check-in attendee
GET http://localhost:3333/attendees/gcg23d/check-in

###

# Get event attendee
GET http://localhost:3333/events/bef2c7e9-feb1-49b7-a127-d0791e09bd5b/attendees?query=ana
