POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Py NE",
    "details": "Evento de Py no Nordeste",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/9a3f9666-f6ae-446a-82ff-c488e535a399/attendees
Content-Type: application/json

{
    "name": "Ivamberg Fernandes",
    "socialName": "",
    "email": "d.braino@rocketseat.com",
    "age": 29,
    "gender": "Masculino",
    "customGender": "",
    "treatAs": "Masculino",
    "accessibility": "Nenhuma"
}

###

GET http://localhost:3333/events/9565b98a-a615-4a00-a69c-20584aaaa1b2

###

GET http://localhost:3333/events/attendees/1/badge

###
GET http://localhost:3333/attendees/11/check-in

###
GET http://localhost:3333/events/9a3f9666-f6ae-446a-82ff-c488e535a399/attendees?query=diego
